---
title: "All"
author: "Gopika Punchhi"
date: "9/2/2019"
output: html_document
---


```{r institute, include=FALSE}

library(plyr)
library(readr)
library(dplyr)
library(tidyverse)


x=read.csv("C:/Users/g_pun/Dropbox/ZeroTB/GTCV/ACF_2018_clean.csv",stringsAsFactors = FALSE, na.strings=TRUE)


##Insitute variable renaming
##need to write this in based on what you see in the document

x$institute[x$institute=="LTCV"]<-1
x$institute[x$institute=="GTCV"]<-3
x$institute[x$institute=="TCV GOPUR"]<-3
x$institute[x$institute=="LTCV"]<-1
x$institute[x$institute=="LTCV"]<-1
```

```{r age}
x$age[x$age=="NA"]<-""
```

```{r sex}
x$sex[grepl("^m", x$sex, ignore.case = TRUE)]<-1
x$sex[grepl("^f", x$sex, ignore.case = TRUE)]<-2

```

```{r main TB Dorm}

x$dorm_[!grepl("^B|^H|^G",x$dorm,ignore.case=TRUE)] <- ""
x$dorm[grepl("^H",x$dorm,ignore.case=TRUE)] <- 1
x$dorm[grepl("^G",x$dorm,ignore.case=TRUE)] <- 3
x$dorm[grepl("^B",x$dorm,ignore.case=TRUE)] <- 2
x$dorm[grepl("^s", x$dorm, ignore.case = TRUE)]<-5
x$dorm[grepl("^d", x$dorm, ignore.case = TRUE)]<-4
x$dorm[grepl("^M", x$dorm, ignore.case=TRUE)]<-6
x$dorm[grepl("^Y", x$dorm, ignore.case=TRUE)]<-7
```

```{r occuapation}
x$occupation[x$occupation=="STUDENT"]<-1
x$occupation[x$occupation=="TEACHER"]<-2
x$occupation[x$occupation=="HEALTH-STAFF"]<-3
x$occupation[x$occupation=="HEALTH STAFF"]<-3
x$occupation[x$occupation=="OFFICE-STAFF"]<-4
x$occupation[x$occupation=="OFFICE STAFF"]<-4
x$occupation[x$occupation=="HOME-MOTHER"]<-5
x$occupation[x$occupation=="HOME MOTHER"]<-5
x$occupation[x$occupation=="MONK"]<-6
x$occupation[x$occupation=="NUN"]<-7
x$occupation[x$occupation=="COOK"]<-8
x$occupation[x$occupation=="DRIVER"]<-9
x$occupation[x$occupation=="HOME-FATHER"]<-10
x$occupation[x$occupation=="HOME FATHER"]<-10
x$occupation[x$occupation=="STAFF"]<-11
```

```{r Country}
x$birth_place[!grepl('^IND|^TIB|^NEP|^BHU|', x$birth_place,ignore.case=TRUE)] <- 5
x$birth_place[x$birth_place=="INDIA"]<-1
x$birth_place[x$birth_place=="TIBET"]<-2
x$birth_place[x$birth_place=="NEPAL"]<-3
x$birth_place[x$birth_place=="BHUTAN"]<-4
x$birth_place[x$birth_place=="USA"]<-5
```


```{r prev tb}
x$prev_tb[x$prev_tb=="NO"]<-0
x$prev_tb[x$prev_tb=="YES"]<-1
x$prev_tb[x$prev_tb=="UNKNOWN"]<-9
x$prev_tb[x$prev_tb=="NA"]<-9

```

```{r year of previous TB}
x$prevtb_year[x$prevtb_year=="NA"]<-99
x$prevtb_year[x$prevtb_year=="UNKNOWN"]<-9
```


```{r prev tb type}
x$prevtb_type[x$prevtb_type=="NON MDR"]<-0
x$prevtb_type[grepl("^no",x$prevtb_type, ignore.case = TRUE)]<-0
x$prevtb_type[x$prevtb_type=="MDR"]<-1
x$prevtb_type[grepl("^md",x$prevtb_type, ignore.case = TRUE)]<-1
x$prevtb_type[x$prevtb_type=="NA"]<-""

```



```{r seizures}
x$seizures[x$seizures=="NO"]<-0
x$seizures[x$seizures=="no"]<-0
x$seizures[x$seizures=="YES"]<-1
x$seizures[x$seizures=="yes"]<-1
```

```{r hepb}
x$hepb[x$hepb=="NO"]<-0
x$hepb[x$hepb=="YES"]<-1
x$hepb[x$hepb=="no"]<-0
x$hepb[x$hepb=="yes"]<-1
```

```{r preg_breastfeed}
x$preg_breastfeed[x$preg_breastfeed=="NO"]<-0
x$preg_breastfeed[x$preg_breastfeed=="PREG"]<-1
x$preg_breastfeed[grepl("^bre", x$preg_breastfeed, ignore.case = TRUE)]<-2
x$preg_breastfeed[x$preg_breastfeed=="BREASTFEED"]<-2
```

```{r other comorbid}
x$other_cormorbid[grepl("^no", x$other_cormorbid, ignore.case = TRUE)]<-0
x$other_cormorbid[x$other_cormorbid=="DM"]<-1
x$other_cormorbid[x$other_cormorbid=="HTN"]<-2
x$other_cormorbid[x$other_cormorbid=="DM_HTN"]<-3
x$other_cormorbid[grepl("^o", x$other_cormorbid, ignore.case = TRUE)]<-4
```

```{r longterm med}
x$longterm_med[x$longterm_med=="NONE"]<-0
x$longterm_med[x$longterm_med=="NO"]<-0
x$longterm_med[x$longterm_med=="ANTI-HEPB"]<-1
x$longterm_med[x$longterm_med=="ANTI_SEIZURE"]<-2
x$longterm_med[x$longterm_med=="ANTI-SEIZURE"]<-2
x$longterm_med[x$longterm_med=="ANTI_DM"]<-3
x$longterm_med[x$longterm_med=="ANTI-HTN"]<-4
x$longterm_med[x$longterm_med=="ANTI-DMHTN"]<-5
x$longterm_med[x$longterm_med=="ANTI-HEPBDM"]<-6
x$longterm_med[x$longterm_med=="ANTI-HEPHTN"]<-7
x$longterm_med[x$longterm_med=="ANTI-HEPBSEIZURE"]<-8
x$longterm_med[x$longterm_med=="ANTI-SEIZUREDM"]<-9
x$longterm_med[x$longterm_med=="ANTI_SEIZUREHTN"]<-10
x$longterm_med[x$longterm_med=="OTHER"]<-11
```

```{r eversmoked}
x$ever_smoked[x$ever_smoked=="NO"]<-0
x$ever_smoked[x$ever_smoked=="YES"]<-1
```

```{r bcg tibetborn}
x$bcg_tibetborn[x$bcg_tibetborn=="NO"]<-0
x$bcg_tibetborn[x$bcg_tibetborn=="YES"]<-1
x$bcg_tibetborn[x$bcg_tibetborn=="NA"]<-""
```

```{r contact with TB in last two years}
x$contactsch_2yr[x$contactsch_2yr=="NO"]<-0
x$contactsch_2yr[x$contactsch_2yr=="YES"]<-1
x$contactsch_2yr[x$contactsch_2yr=="UNKNOWN"]<-2
```

```{r drug sensitivity of Tb case at school}
x$indexcasesch_tbtype[x$indexcasesch_tbtype=="NON MDR"]<-0
x$indexcasesch_tbtype[x$indexcasesch_tbtype=="MDR"]<-1
x$indexcasesch_tbtype[x$indexcasesch_tbtype==""]<-""
x$indexcasesch_tbtype[x$indexcasesch_tbtype=="UNKNOWN"]<-9
x$indexcasesch_tbtype[x$indexcasesch_tbtype=="NA"]<-99

```

```{r index case at school}
x$indexcasesch_is[x$indexcasesch_is=="CLASS MATE"]<-1
x$indexcasesch_is[x$indexcasesch_is=="CLASS-MATE"]<-1
x$indexcasesch_is[x$indexcasesch_is=="CLASSMATE"]<-1
x$indexcasesch_is[x$indexcasesch_is=="DORM MATE"]<-2
x$indexcasesch_is[x$indexcasesch_is=="DORMMATE"]<-2
x$indexcasesch_is[x$indexcasesch_is=="DORM-MATE"]<-2
x$indexcasesch_is[x$indexcasesch_is=="CLASSDORM MATE"]<-3
x$indexcasesch_is[x$indexcasesch_is=="CLASS DORM MATE"]<-3
x$indexcasesch_is[x$indexcasesch_is=="CLASS DORM-MATE"]<-3
x$indexcasesch_is[x$indexcasesch_is=="SCHOOL STAFF"]<-4
x$indexcasesch_is[x$indexcasesch_is=="SCHOOL-STAFF"]<-4
x$indexcasesch_is[x$indexcasesch_is=="FRIEND"]<-5
x$indexcasesch_is[x$indexcasesch_is=="OTHER"]<-6
x$indexcasesch_is[x$indexcasesch_is=="NA"]<-99

x$indexcasesch_count[x$indexcasesch_count=="0"]<-0
x$indexcasesch_count[x$indexcasesch_count=="1"]<-1
x$indexcasesch_count[x$indexcasesch_count=="2"]<-2
x$indexcasesch_count[x$indexcasesch_count=="3"]<-3
x$indexcasesch_count[x$indexcasesch_count=="4"]<-3
x$indexcasesch_count[grepl("^>",x$indexcasesch_count, ignore.case=FALSE)]<-3
x$indexcasesch_count[x$indexcasesch_count=="NA"]<-""

```

```{r exposed to TB athome}
x$contacthome_2yr[x$contacthome_2yr=="NO"]<-0
x$contacthome_2yr[x$contacthome_2yr=="YES"]<-1
x$contacthome_2yr[x$contacthome_2yr=="UNKNOWN"]<-2


```

```{r drug sensitivity of the TB case at home}
x$indexcasehome_tbtype[x$indexcasehome_tbtype=="NON MDR"]<-0
x$indexcasehome_tbtype[x$indexcasehome_tbtype=="MDR"]<-1
x$indexcasehome_tbtype[x$indexcasehome_tbtype=="UNKNOWN"]<-9
x$indexcasehome_tbtype[x$indexcasehome_tbtype=="NA"]<-99

```

```{r index case at home}
x$indexcasehome_is[x$indexcasehome_is=="PARENT"]<-1
x$indexcasehome_is[x$indexcasehome_is=="SIBLING"]<-2
x$indexcasehome_is[x$indexcasehome_is=="GRANDPARENT"]<-3
x$indexcasehome_is[x$indexcasehome_is=="GRAND PARENT"]<-3
x$indexcasehome_is[x$indexcasehome_is=="OTHER"]<-4
x$indexcasehome_is[x$indexcasehome_is=="NA"]<-99
```

```{r indexcasehome_count}
x$indexcasehome_count[x$indexcasehome_count=="0"]<-0
x$indexcasehome_count[x$indexcasehome_count=="1"]<-1
x$indexcasehome_count[x$indexcasehome_count=="2"]<-2
x$indexcasehome_count[x$indexcasehome_count=="3"]<-3
x$indexcasehome_count[x$indexcasehome_count==">3"]<-3
x$indexcasehome_count[x$indexcasehome_count>="NA"]<-99

#### CHECK THIS LAST LINE OF CODE
```

```{r presence of cough}
x$cough[x$cough=="NO"]<-0
x$cough[x$cough=="YES"]<-1
```


```{r cough duration in weeks}
x$coughduration_wks[grepl("^l", x$coughduration_wks, ignore.case=TRUE)]<-1
x$coughduration_wks[grepl("^o", x$coughduration_wks, ignore.case=TRUE)]<-2
x$coughduration_wks[grepl("^t", x$coughduration_wks, ignore.case=TRUE)]<-3
x$coughduration_wks[grepl("^g", x$coughduration_wks, ignore.case=TRUE)]<-4
x$coughduration_wks[!grepl("^o|^t|^g", x$coughduration_wks, ignore.case=TRUE)]<-""
x$coughduration_wks[x$coughduration_wks=="NA"]<-99

```

```{r patient cough productive}
x$productive_cough[x$productive_cough=="NO"]<-0
x$productive_cough[x$productive_cough=="YES"]<-1
x$productive_cough[x$productive_cough=="NA"]<-99
```

```{r presence of blood in sputum}
x$blood_sputum[x$blood_sputum=="NO"]<-0
x$blood_sputum[x$blood_sputum=="YES"]<-1
x$blood_sputum[x$blood_sputum=="NA"]<-99
```

```{r fever}
x$fever[x$fever=="NO"]<-0
x$fever[x$fever=="YES"]<-1
```

```{r fever duration}
x$fever_duration[grepl("^l", x$fever_duration, ignore.case = TRUE)]<-1
x$fever_duration[grepl("^o", x$fever_duration, ignore.case = TRUE)]<-2
x$fever_duration[grepl("^g", x$fever_duration, ignore.case = TRUE)]<-3
x$fever_duration[!grepl("^l|^o|^g", x$fever_duration, ignore.case = TRUE)]<-""
x$fever_duration[x$fever_duration=="NA"]<-4
```

```{r presence of night sweats}
x$nightsweats_2wks[x$nightsweats_2wks=="NO"]<-0
x$nightsweats_2wks[x$nightsweats_2wks=="YES"]<-1
```

```{r weight loss in year prior}
x$wtloss_1month[x$wtloss_1month=="NO"]<-0
x$wtloss_1month[x$wtloss_1month=="YES"]<-1
```

```{r fatigue prior 2 weeks}
x$fatigue_last2wks[x$fatigue_last2wks=="NO"]<-0
x$fatigue_last2wks[x$fatigue_last2wks=="YES"]<-1
```

```{r ongoing chest pain}
x$chestpain_current[x$chestpain_current=="NO"]<-0
x$chestpain_current[x$chestpain_current=="YES"]<-1
```


```{r previous tst done}
x$tst1_done[x$tst1_done=="YES"]<-1
x$tst1_done[x$tst1_done=="PREV TB"]<-2
x$tst1_done[x$tst1_done=="PREVTB"]<-2
x$tst1_done[grepl("^pr", x$tst1_done, ignore.case=TRUE)]<-2
x$tst1_done[x$tst1_done=="NOT INDICATED"]<-3
x$tst1_done[x$tst1_done=="NOTINDICATED"]<-3
x$tst1_done[x$tst1_done=="NA"]<-3
x$tst1_done[x$tst1_done=="REFUSED"]<-4
```

```{r wheal size}
x$wheal1_size[x$wheal1_size=="NA"]<-""
```

```{r date}
x$xpert1_date[x$xpert1_date=="NA"]<-""
```

```{r type of specimen xpert}
x$xpert1_specimen[x$xpert1_specimen=="SPUTUM"]<-1
x$xpert1_specimen[x$xpert1_specimen=="GA"]<-2
x$xpert1_specimen[grepl("^GA", x$xpert1_specimen, ignore.case = FALSE)]<-2
x$xpert1_specimen[x$xpert1_specimen=="PUS"]<-3
x$xpert1_specimen[x$xpert1_specimen=="PLEURAL FLUID"]<-4
x$xpert1_specimen[x$xpert1_specimen=="URINE"]<-5
x$xpert1_specimen[x$xpert1_specimen=="CSF"]<-6
x$xpert1_specimen[x$xpert1_specimen=="NA"]<-99
```

```{r result of xpert analysis}
x$xpert1_result[x$xpert1_result=="NOT DETECTED"]<-0
x$xpert1_result[x$xpert1_result=="NEGATIVE"]<-0
x$xpert1_result[x$xpert1_result=="DETECTED"]<-1
x$xpert1_result[x$xpert1_result=="POSITIVE"]<-1
x$xpert1_result[x$xpert1_result=="NA"]<-99
```

```{r drug sensitivty as per xpert analysis}
x$xpert1_mtb[x$xpert1_mtb=="VL"]<-0
x$xpert1_mtb[x$xpert1_mtb=="LOW"]<-1
x$xpert1_mtb[x$xpert1_mtb=="MED"]<-2
x$xpert1_mtb[x$xpert1_mtb=="HIGH"]<-3
x$xpert1_mtb[x$xpert1_mtb=="NA"]<-99

```

```{r rifampin resistance}
x$xpert1_rif[x$xpert1_rif=="SEN"]<-0
x$xpert1_rif[grepl("^s", x$xpert1_rif, ignore.case = TRUE)]<-0
x$xpert1_rif[x$xpert1_rif=="SENSITIVE"]<-0
x$xpert1_rif[x$xpert1_rif=="RES"]<-1
x$xpert1_rif[grepl("^r", x$xpert1_rif, ignore.case = TRUE)]<-1
x$xpert1_rif[x$xpert1_rif=="INDET"]<-2
x$xpert1_rif[grepl("^i", x$xpert1_rif, ignore.case = TRUE)]<-2
x$xpert1_rif[x$xpert1_rif=="NA"]<-99
```

```{r xpert2 date}
x$xpert2_date[x$xpert2_date=="NA"]<-""
```

```{r type of spec use for 2nd xpert}
x$xpert2_specimen[x$xpert2_specimen=="SPUTUM"]<-1
x$xpert2_specimen[x$xpert2_specimen=="GA"]<-2
x$xpert2_specimen[x$xpert2_specimen=="PUS"]<-3
x$xpert2_specimen[x$xpert2_specimen=="PLEURAL FLUID"]<-4
x$xpert2_specimen[x$xpert2_specimen=="URINE"]<-5
x$xpert2_specimen[x$xpert2_specimen=="CSF"]<-6
x$xpert2_specimen[x$xpert2_specimen=="NA"]<-99
```

```{r result of xpert2}
x$xpert2_result[x$xpert2_result=="NOT DETECTED"]<-0
x$xpert2_result[x$xpert2_result=="NEGATIVE"]<-0
x$xpert2_result[x$xpert2_result=="DETECTED"]<-1
x$xpert2_result[x$xpert2_result=="POSITIVE"]<-1
x$xpert2_result[x$xpert2_result=="NA"]<-99
```


```{r drug sensitivty as per xpert2 analysis}
x$xpert2_mtb[x$xpert2_mtb=="VL"]<-0
x$xpert2_mtb[x$xpert2_mtb=="LOW"]<-1
x$xpert2_mtb[x$xpert2_mtb=="MED"]<-2
x$xpert2_mtb[x$xpert2_mtb=="HIGH"]<-3
x$xpert2_mtb[x$xpert2_mtb=="NA"]<-99
```

```{r rifampin resistance 2}
x$xpert2_rif[x$xpert2_rif=="SEN"]<-0
x$xpert2_rif[grepl("^s", x$xpert2_rif, ignore.case = TRUE)]<-0
x$xpert2_rif[x$xpert2_rif=="SENSITIVE"]<-0
x$xpert2_rif[x$xpert2_rif=="RES"]<-1
x$xpert2_rif[grepl("^r", x$xpert2_rif, ignore.case = TRUE)]<-1
x$xpert2_rif[x$xpert2_rif=="INDET"]<-2
x$xpert2_rif[grepl("^i", x$xpert2_rif, ignore.case = TRUE)]<-2
x$xpert2_rif[x$xpert2_rif=="NA"]<-99

```

```{r cxr}
x$cxr[x$cxr=="NA"]<-""
```

```{r cxr result}
x$cxr_result[x$cxr_result=="NORMAL"]<-0
x$cxr_result[x$cxr_result=="ABNORMAL"]<-1
x$cxr_result[x$cxr_result=="NA"]<-""
```

```{r diagnosed with active TB}
x$tb_diagnosed[x$tb_diagnosed=="NO"]<-0
x$tb_diagnosed[x$tb_diagnosed=="YES"]<-1
x$tb_diagnosed[x$tb_diagnosed=="NA"]<-""

```

```{r total num of students}
x$total_students[x$total_students=="NA"]<-""
```

```{r total staff}
x$total_monks_nuns[x$total_monks_nuns=="NA"]<-""
```

```{r notes main}
x$notes_main[x$notes_main=="NA"]<-""
```

```{r demographics}
x$main_database_demographics_complete<-2
x$main_database_tbinvestigation_complete<-2
x$active_tb_tbinvestigation_complete<-2
x$tst_reactive_treatment_complete<-2

```

```{r active}
library(plyr)
library(readr)
library(dplyr)
library(tidyverse)
library(lubridate)
```

```{r Active Tb Tbinvestigation}
x$prev_tb_activetb[x$prev_tb_activetb=="NO"]<-0
x$prev_tb_activetb[x$prev_tb_activetb=="YES"]<-1
x$prev_tb_activetb[x$prev_tb_activetb=="UNKNOWN"]<-9

x$prevtb_year_activetb[x$prevtb_year_activetb=="UNKNOWN"]<-9
x$prevtb_year_activetb[x$prevtb_year_activetb=="NA"]<-99

x$prevtb_site_activetb[x$prevtb_site_activetb=="UNKNOWN"]<-9
x$prevtb_site_activetb[x$prevtb_site_activetb=="NA"]<-99

x$comorbidity[x$comorbidity=="None"]<-0
x$comorbidity[x$comorbidity=="NONE"]<-0
x$comorbidity[x$comorbidity=="NO"]<-0
x$comorbidity[x$comorbidity=="DM"]<-1
x$comorbidity[x$comorbidity=="HTN"]<-2
x$comorbidity[x$comorbidity=="DM_HTN"]<-3
x$comorbidity[x$comorbidity=="Other"]<-4
x$comorbidity[x$comorbidity=="OTHER"]<-4
x$comorbidity[x$comorbidity=="NA"]<-""

x$chronic_meds[x$chronic_meds=="NO"]<-0
x$chronic_meds[x$chronic_meds=="YES"]<-1

x$ever_smoked_activetb[x$ever_smoked_activetb=="NO"]<-0
x$ever_smoked_activetb[x$ever_smoked_activetb=="YES"]<-1

x$bcg_tibetborn_activetb[x$bcg_tibetborn_activetb=="NO"]<-0
x$bcg_tibetborn_activetb[x$bcg_tibetborn_activetb=="YES"]<-1
  
x$contact_sch_oneyr[x$contact_sch_oneyr=="NO"]<-0
x$contact_sch_oneyr[x$contact_sch_oneyr=="YES"]<-1
x$contact_sch_oneyr[x$contact_sch_oneyr=="UNKNOWN"]<-9
x$contact_sch_oneyr[x$contact_sch_oneyr=="NA"]<-99

x$indexcasesch_lung_pleura[x$indexcasesch_lung_pleura=="NO"]<-0
x$indexcasesch_lung_pleura[grepl("^n", x$indexcasesch_lung_pleura, ignore.case = TRUE)]<-0
x$indexcasesch_lung_pleura[grepl("^l", x$indexcasesch_lung_pleura, ignore.case = TRUE)]<-1
x$indexcasesch_lung_pleura[x$indexcasesch_lung_pleura=="NA"]<-99

x$indexcasesch_sputumstatus[grepl("^N",x$indexcasesch_sputumstatus,ignore.case=FALSE)] <- 0
x$indexcasesch_sputumstatus[grepl("^n",x$indexcasesch_sputumstatus,ignore.case=FALSE)] <- 0
x$indexcasesch_sputumstatus[grepl("^P",x$indexcasesch_sputumstatus,ignore.case=FALSE)] <- 1
x$indexcasesch_sputumstatus[grepl("^p",x$indexcasesch_sputumstatus,ignore.case=FALSE)] <- 1
x$indexcasesch_sputumstatus[x$indexcasesch_sputumstatus=="UNKNOWN"]<-9
x$indexcasesch_sputumstatus[x$indexcasesch_sputumstatus=="NA"]<-99

x$indexcasesch_cough[x$indexcasesch_cough=="NO"]<-0
x$indexcasesch_cough[x$indexcasesch_cough=="YES"]<-1

x$sharedroom_with_indexcasesch[x$sharedroom_with_indexcasesch=="NO"]<-0
x$sharedroom_with_indexcasesch[x$sharedroom_with_indexcasesch=="YES"]<-1

x$relation_with_indexcasesch[x$relation_with_indexcasesch=="CLASS-MATE"]<-1
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="CLASS MATE"]<-1
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="DORM-MATE"]<-2
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="DORM MATE"]<-2
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="CLASSDORM-MATE"]<-3
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="CLASSDORM MATE"]<-3
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="SCHOOL-STAFF"]<-4
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="SCHOOL STAFF"]<-4
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="FRIEND"]<-5
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="OTHER"]<-6
x$relation_with_indexcasesch[x$relation_with_indexcasesch=="NA"]<-99

x$indexcasesch_count_activetb[x$indexcasesch_count_activetb=="0"]<-0
x$indexcasesch_count_activetb[x$indexcasesch_count_activetb=="1"]<-1
x$indexcasesch_count_activetb[x$indexcasesch_count_activetb=="2"]<-2
x$indexcasesch_count_activetb[x$indexcasesch_count_activetb=="3"]<-3
x$indexcasesch_count_activetb[grepl("^>",x$indexcasesch_count_activetb, ignore.case=FALSE)]<-3
x$indexcasesch_count_activetb[x$indexcasesch_count_activetb=="NA"]<-99

x$contacthome_2yr_activetb[x$contacthome_2yr_activetb=="NO"]<-0
x$contacthome_2yr_activetb[x$contacthome_2yr_activetb=="YES"]<-1
x$contacthome_2yr_activetb[x$contacthome_2yr_activetb=="UNKNOWN"]<-2


x$indexcasehome_lung[x$indexcasehome_lung=="NO"]<-0
x$indexcasehome_lung[x$indexcasehome_lung=="YES"]<-1
x$indexcasehome_lung[x$indexcasehome_lung=="NA"]<-99

x$indexcasehome_sputumstatus[x$indexcasehome_sputumstatus=="NEGATIVE"]<-0
x$indexcasehome_sputumstatus[x$indexcasehome_sputumstatus=="POSITIVE"]<-1
x$indexcasehome_sputumstatus[x$indexcasehome_sputumstatus=="NOT DONE"]<-2
x$indexcasehome_sputumstatus[x$indexcasehome_sputumstatus=="UNKNOWN"]<-9

x$indexcasehome_cough[x$indexcasehome_cough=="NO"]<-0
x$indexcasehome_cough[x$indexcasehome_cough=="YES"]<-1
x$indexcasehome_cough[x$indexcasehome_cough=="NA"]<-99

x$sharedroom_with_indexcasehome[x$sharedroom_with_indexcasehome=="NO"]<-0
x$sharedroom_with_indexcasehome[x$sharedroom_with_indexcasehome=="YES"]<-1

x$relation_with_indexcasehome[x$relation_with_indexcasehome=="PARENT"]<-1
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="SIBLING"]<-2
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="GRANDPARENT"]<-3
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="GRAND PARENT"]<-3
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="OTHER"]<-4
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="NA"]<-99

x$indexcasehome_count_activetb[x$indexcasehome_count_activetb=="0"]<-0
x$indexcasehome_count_activetb[x$indexcasehome_count_activetb=="1"]<-1
x$indexcasehome_count_activetb[x$indexcasehome_count_activetb=="2"]<-2
x$indexcasehome_count_activetb[x$indexcasehome_count_activetb=="3"]<-3
x$indexcasehome_count_activetb[x$indexcasehome_count_activetb==">3"]<-3
x$indexcasehome_count_activetb[x$indexcasehome_count_activetb=="NA"]<-""

x$relation_with_indexcasehome[x$relation_with_indexcasehome=="PARENT"]<-1
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="SIBLING"]<-2
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="GRANDPARENT"]<-3
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="GRAND PARENT"]<-3
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="OTHER"]<-4
x$relation_with_indexcasehome[x$relation_with_indexcasehome=="NA"]<-99
```

```{r Active TB Cough}
x$cough_activetb[grepl("NA",x$cough_activetb,ignore.case=FALSE)] <- ""
x$cough_activetb[grepl("^N",x$cough_activetb,ignore.case=FALSE)] <- 0
x$cough_activetb[grepl("^Y",x$cough_activetb,ignore.case=FALSE)] <- 1
x$cough_activetb[grepl("^n",x$cough_activetb,ignore.case=FALSE)] <- 0
x$cough_activetb[grepl("^y",x$cough_activetb,ignore.case=FALSE)] <- 1

x$coughduration_wks_activetb[grepl("NA",x$coughduration_wks_activetb,ignore.case=FALSE)] <-99
x$coughduration_wks_activetb[grepl("^GE",x$coughduration_wks_activetb,ignore.case=FALSE)] <- 4
x$coughduration_wks_activetb[grepl("^LT",x$coughduration_wks_activetb,ignore.case=FALSE)] <- 1
x$coughduration_wks_activetb[grepl("^ONE-TW",x$coughduration_wks_activetb,ignore.case=FALSE)] <- 2
x$coughduration_wks_activetb[grepl("^1-2",x$coughduration_wks_activetb,ignore.case=FALSE)] <- 2
x$coughduration_wks_activetb[grepl("^2-3",x$coughduration_wks_activetb,ignore.case=FALSE)] <- 3
x$coughduration_wks_activetb[grepl("^TWO-THRE",x$coughduration_wks_activetb,ignore.case=FALSE)] <- 3

x$productive_cough_activetb[grepl("NA",x$productive_cough_activetb,ignore.case=FALSE)] <-99
x$productive_cough_activetb[grepl("^N",x$productive_cough_activetb,ignore.case=FALSE)] <- 0
x$productive_cough_activetb[grepl("^n",x$productive_cough_activetb,ignore.case=FALSE)] <- 0
x$productive_cough_activetb[grepl("^Y",x$productive_cough_activetb,ignore.case=FALSE)] <- 1
x$productive_cough_activetb[grepl("^y",x$productive_cough_activetb,ignore.case=FALSE)] <- 1

x$blood_sputum_activetb[grepl("NA",x$blood_sputum_activetb,ignore.case=FALSE)] <-99
x$blood_sputum_activetb[grepl("^N",x$blood_sputum_activetb,ignore.case=FALSE)] <- 0
x$blood_sputum_activetb[grepl("^n",x$blood_sputum_activetb,ignore.case=FALSE)] <- 0
x$blood_sputum_activetb[grepl("^Y",x$blood_sputum_activetb,ignore.case=FALSE)] <- 1
x$blood_sputum_activetb[grepl("^y",x$blood_sputum_activetb,ignore.case=FALSE)] <- 1

x$fever_activetb[grepl("NA",x$fever_activetb,ignore.case=FALSE)] <- ""
x$fever_activetb[grepl("^N",x$fever_activetb,ignore.case=FALSE)] <- 0
x$fever_activetb[grepl("^n",x$fever_activetb,ignore.case=FALSE)] <- 0
x$fever_activetb[grepl("^Y",x$fever_activetb,ignore.case=FALSE)] <- 1
x$fever_activetb[grepl("^y",x$fever_activetb,ignore.case=FALSE)] <- 1

x$fever_duration_activetb[grepl("NA",x$fever_duration_activetb,ignore.case=FALSE)] <- 4
x$fever_duration_activetb[grepl("^GE",x$fever_duration_activetb,ignore.case=FALSE)] <- 3
x$fever_duration_activetb[grepl("^LT",x$fever_duration_activetb,ignore.case=FALSE)] <- 1
x$fever_duration_activetb[grepl("^ONE",x$fever_duration_activetb,ignore.case=FALSE)] <- 2
x$fever_duration_activetb[grepl("^1",x$fever_duration_activetb,ignore.case=FALSE)] <- 2

x$nightsweats_2wks_activetb[grepl("NA",x$nightsweats_2wks_activetb,ignore.case=TRUE)] <- ""
x$nightsweats_2wks_activetb[grepl("^N",x$nightsweats_2wks_activetb,ignore.case=TRUE)] <- 0
x$nightsweats_2wks_activetb[grepl("^Y",x$nightsweats_2wks_activetb,ignore.case=TRUE)] <- 1


x$wtloss_1month_activetb[grepl("NA",x$wtloss_1month_activetb,ignore.case=TRUE)] <- ""
x$wtloss_1month_activetb[grepl("^N",x$wtloss_1month_activetb,ignore.case=TRUE)] <- 0
x$wtloss_1month_activetb[grepl("^Y",x$wtloss_1month_activetb,ignore.case=TRUE)] <- 1

x$fatigue_last2wks_activetb[grepl("NA",x$fatigue_last2wks_activetb,ignore.case=TRUE)] <- ""
x$fatigue_last2wks_activetb[grepl("^N",x$fatigue_last2wks_activetb,ignore.case=TRUE)] <- 0
x$fatigue_last2wks_activetb[grepl("^Y",x$fatigue_last2wks_activetb,ignore.case=TRUE)] <- 1

x$tst1_done_activeb[x$tst1_done_activetb=="YES"]<-1
x$tst1_done_activeb[x$tst1_done_activetb=="PREVTB"]<-2
x$tst1_done_activeb[x$tst1_done_activetb=="PREV TB"]<-2
x$tst1_done_activeb[x$tst1_done_activetb=="NOT INDICATED"]<-3
x$tst1_done_activeb[x$tst1_done_activetb=="REFUSED"]<-4

x$tst1_result[x$tst1_result=="NEGATIVE"]<-0
x$tst1_result[x$tst1_result=="POSITIVE"]<-1
x$tst1_result[x$tst1_result=="NOT DONE"]<-2
x$tst1_result[x$tst1_result=="UNKNOWN"]<-9

x$tst_adr[x$tst_adr=="NONE"]<-0
x$tst_adr[x$tst_adr=="NO"]<-0
x$tst_adr[x$tst_adr=="YES"]<-1


x$xpert_specimen[grepl("NA",x$xpert_specimen,ignore.case=TRUE)] <-99
x$xpert_specimen[grepl("^SPU",x$xpert_specimen,ignore.case=TRUE)] <- 1
x$xpert_specimen[grepl("^GASTRIC",x$xpert_specimen,ignore.case=TRUE)] <- 2
x$xpert_specimen[x$xpert_specimen=="GASTRIC ASPIRATION"]<-2
x$xpert_specimen[grepl("^GA",x$xpert_specimen,ignore.case=TRUE)] <- 2
x$xpert_specimen[grepl("^PU",x$xpert_specimen,ignore.case=TRUE)] <- 3
x$xpert_specimen[grepl("^PLEURAL",x$xpert_specimen,ignore.case=TRUE)] <- 4
x$xpert_specimen[grepl("^UR",x$xpert_specimen,ignore.case=TRUE)] <- 5
x$xpert_specimen[grepl("^CSF",x$xpert_specimen,ignore.case=TRUE)] <- 6

x$xpert_result[grepl("NA",x$xpert_result,ignore.case=TRUE)] <-99
x$xpert_result[grepl("^N",x$xpert_result,ignore.case=TRUE)] <- 0
x$xpert_result[grepl("^D",x$xpert_result,ignore.case=TRUE)] <- 1
x$xpert_result[grepl("^P",x$xpert_result,ignore.case=TRUE)] <- 1

x$xpert_mtb[grepl("NA",x$xpert_mtb,ignore.case=TRUE)] <-99
x$xpert_mtb[grepl("^V",x$xpert_mtb,ignore.case=TRUE)] <- 0
x$xpert_mtb[grepl("^L",x$xpert_mtb,ignore.case=TRUE)] <- 1
x$xpert_mtb[grepl("^M",x$xpert_mtb,ignore.case=TRUE)] <- 2
x$xpert_mtb[grepl("^H",x$xpert_mtb,ignore.case=TRUE)] <- 3

x$xpert_rif[grepl("NA",x$xpert_rif,ignore.case=TRUE)] <-99
x$xpert_rif[grepl("^S",x$xpert_rif,ignore.case=TRUE)] <- 0
x$xpert_rif[grepl("^R",x$xpert_rif,ignore.case=TRUE)] <- 1
x$xpert_rif[grepl("^I",x$xpert_rif,ignore.case=TRUE)] <- 2

x$tb_diagnosis[x$tb_diagnosis=="NO"]<-0
x$tb_diagnosis[x$tb_diagnosis=="YES"]<-1

x$sch_mon_prev1yr[x$sch_mon_prev1yr=="TCV LADHAK"]<-20
x$sch_mon_prev1yr[x$sch_mon_prev1yr=="BYLAKUPPE"]<-19
x$sch_mon_prev1yr[x$sch_mon_prev1yr=="SELAQUI"]<-12
x$sch_mon_prev1yr[x$sch_mon_prev1yr=="GTCV"]<-3
x$sch_mon_prev1yr[x$sch_mon_prev1yr=="LTCV"]<-1

x$patient_type[x$patient_type=="NEW"]<-1
x$patient_type[grepl("^RE", x$patient_type, ignore.case = TRUE)]<-2

x$disease_site[grepl("NA",x$disease_site,ignore.case=TRUE)] <- ""
x$disease_site[grepl("LUNG",x$disease_site,ignore.case=TRUE)] <-1
x$disease_site[grepl("^PLE",x$disease_site,ignore.case=TRUE)] <-2
x$disease_site[grepl("LUNG & PLEURA",x$disease_site,ignore.case=TRUE)] <-3
x$disease_site[grepl("^LYMPH",x$disease_site,ignore.case=TRUE)] <-4
x$disease_site[grepl("^AB",x$disease_site,ignore.case=TRUE)] <-5
x$disease_site[grepl("^SP",x$disease_site,ignore.case=TRUE)] <-6
x$disease_site[grepl("^BONE",x$disease_site,ignore.case=TRUE)] <-7
x$disease_site[grepl("OTHER BONE",x$disease_site,ignore.case=TRUE)] <-7
x$disease_site[grepl("OTHER",x$disease_site,ignore.case=TRUE)] <-9

x$category[grepl("NA",x$category,ignore.case=TRUE)] <- ""
x$category[grepl("^CAT-1",x$category,ignore.case=TRUE)] <- 1
x$category[grepl("^CAT-2",x$category,ignore.case=TRUE)] <- 2
x$category[grepl("^CAT-4",x$category,ignore.case=TRUE)] <- 3
x$category[grepl("^IN",x$category,ignore.case=TRUE)] <- 4
x$category[grepl("^NT",x$category,ignore.case=TRUE)] <- 5

x$diagnostic_smear[grepl("^NA",x$diagnostic_smear,ignore.case=TRUE)] <- ""
x$diagnostic_smear[grepl("^UNKNO",x$diagnostic_smear,ignore.case=TRUE)] <- 9
x$diagnostic_smear[grepl("^P",x$diagnostic_smear,ignore.case=TRUE)] <- 1
x$diagnostic_smear[grepl("^N",x$diagnostic_smear,ignore.case=TRUE)] <- 0
x$diagnostic_smear[grepl("^NOT",x$diagnostic_smear,ignore.case=TRUE)] <- 2

x$hiv[grepl("^NA",x$hiv,ignore.case=TRUE)] <- ""
x$hiv[grepl("^N",x$hiv,ignore.case=TRUE)] <- 0
x$hiv[grepl("^P",x$hiv,ignore.case=TRUE)] <- 1
x$hiv[grepl("^NOT",x$hiv,ignore.case=TRUE)] <- 2
x$hiv[grepl("^UNK",x$hiv,ignore.case=TRUE)] <- 9

x$hep_b[grepl("^NA",x$hep_b,ignore.case=TRUE)] <- ""
x$hep_b[grepl("^N",x$hep_b,ignore.case=TRUE)] <- 0
x$hep_b[grepl("^P",x$hep_b,ignore.case=TRUE)] <- 1
x$hep_b[grepl("^NOT",x$hep_b,ignore.case=TRUE)] <- 2
x$hep_b[grepl("^UNK",x$hep_b,ignore.case=TRUE)] <- 9

x$culture_result[grepl("^NA",x$culture_result,ignore.case=TRUE)] <- ""
x$culture_result[grepl("^NO",x$culture_result,ignore.case=TRUE)] <- 3
x$culture_result[grepl("^N",x$culture_result,ignore.case=TRUE)] <- 0
x$culture_result[grepl("^P",x$culture_result,ignore.case=TRUE)] <- 1
x$culture_result[grepl("^NOT",x$culture_result,ignore.case=TRUE)] <- 2
x$culture_result[grepl("^UNK",x$culture_result,ignore.case=TRUE)] <- 9

x$dst_inh[grepl("^NA",x$dst_inh,ignore.case=TRUE)] <- ""
x$dst_inh[grepl("^SEN",x$dst_inh,ignore.case=TRUE)] <- 0
x$dst_inh[grepl("^RES",x$dst_inh,ignore.case=TRUE)] <- 1
x$dst_inh[grepl("^NOT",x$dst_inh,ignore.case=TRUE)] <- 2
x$dst_inh[grepl("^UNK",x$dst_inh,ignore.case=TRUE)] <- 9

x$dst_rif[grepl("^NA",x$dst_rif,ignore.case=TRUE)] <- ""
x$dst_rif[grepl("^SEN",x$dst_rif,ignore.case=TRUE)] <- 0
x$dst_rif[grepl("^RES",x$dst_rif,ignore.case=TRUE)] <- 1
x$dst_rif[grepl("^NOT",x$dst_rif,ignore.case=TRUE)] <- 2
x$dst_rif[grepl("^UNK",x$dst_rif,ignore.case=TRUE)] <- 9

x$dst_etham[grepl("^NA",x$dst_etham,ignore.case=TRUE)] <- ""
x$dst_etham[grepl("^SEN",x$dst_etham,ignore.case=TRUE)] <- 0
x$dst_etham[grepl("^RES",x$dst_etham,ignore.case=TRUE)] <- 1
x$dst_etham[grepl("^NOT",x$dst_etham,ignore.case=TRUE)] <- 2
x$dst_etham[grepl("^UNK",x$dst_etham,ignore.case=TRUE)] <- 9

x$dst_pza[grepl("^NA",x$dst_pza,ignore.case=TRUE)] <- ""
x$dst_pza[grepl("^SEN",x$dst_pza,ignore.case=TRUE)] <- 0
x$dst_pza[grepl("^RES",x$dst_pza,ignore.case=TRUE)] <- 1
x$dst_pza[grepl("^NOT",x$dst_pza,ignore.case=TRUE)] <- 2
x$dst_pza[grepl("^UNK",x$dst_pza,ignore.case=TRUE)] <- 9

x$dst_ofx[grepl("^NA",x$dst_ofx,ignore.case=TRUE)] <- ""
x$dst_ofx[grepl("^SEN",x$dst_ofx,ignore.case=TRUE)] <- 0
x$dst_ofx[grepl("^RES",x$dst_ofx,ignore.case=TRUE)] <- 1
x$dst_ofx[grepl("^NOT",x$dst_ofx,ignore.case=TRUE)] <- 2
x$dst_ofx[grepl("^UNK",x$dst_ofx,ignore.case=TRUE)] <- 9

x$dst_mfx[grepl("^NA",x$dst_mfx,ignore.case=TRUE)] <- ""
x$dst_mfx[grepl("^SEN",x$dst_mfx,ignore.case=TRUE)] <- 0
x$dst_mfx[grepl("^RES",x$dst_mfx,ignore.case=TRUE)] <- 1
x$dst_mfx[grepl("^NOT",x$dst_mfx,ignore.case=TRUE)] <- 2
x$dst_mfx[grepl("^UNK",x$dst_mfx,ignore.case=TRUE)] <- 9

x$dst_km[grepl("^NA",x$dst_km,ignore.case=TRUE)] <- ""
x$dst_km[grepl("^SEN",x$dst_km,ignore.case=TRUE)] <- 0
x$dst_km[grepl("^RES",x$dst_km,ignore.case=TRUE)] <- 1
x$dst_km[grepl("^NOT",x$dst_km,ignore.case=TRUE)] <- 2
x$dst_km[grepl("^UNK",x$dst_km,ignore.case=TRUE)] <- 9

x$dst_sm[grepl("^NA",x$dst_sm,ignore.case=TRUE)] <- ""
x$dst_sm[grepl("^SEN",x$dst_sm,ignore.case=TRUE)] <- 0
x$dst_sm[grepl("^RES",x$dst_sm,ignore.case=TRUE)] <- 1
x$dst_sm[grepl("^NOT",x$dst_sm,ignore.case=TRUE)] <- 2
x$dst_sm[grepl("^UNK",x$dst_sm,ignore.case=TRUE)] <- 9

x$dst_am[grepl("^NA",x$dst_am,ignore.case=TRUE)] <- ""
x$dst_am[grepl("^SEN",x$dst_am,ignore.case=TRUE)] <- 0
x$dst_am[grepl("^RES",x$dst_am,ignore.case=TRUE)] <- 1
x$dst_am[grepl("^NOT",x$dst_am,ignore.case=TRUE)] <- 2
x$dst_am[grepl("^UNK",x$dst_am,ignore.case=TRUE)] <- 9

x$dst_cm[grepl("^NA",x$dst_cm,ignore.case=TRUE)] <- ""
x$dst_cm[grepl("^SEN",x$dst_cm,ignore.case=TRUE)] <- 0
x$dst_cm[grepl("^RES",x$dst_cm,ignore.case=TRUE)] <- 1
x$dst_cm[grepl("^NOT",x$dst_cm,ignore.case=TRUE)] <- 2
x$dst_cm[grepl("^UNK",x$dst_cm,ignore.case=TRUE)] <- 9

x$dst_ethio[grepl("^NA",x$dst_ethio,ignore.case=TRUE)] <- ""
x$dst_ethio[grepl("^SEN",x$dst_ethio,ignore.case=TRUE)] <- 0
x$dst_ethio[grepl("^RES",x$dst_ethio,ignore.case=TRUE)] <- 1
x$dst_ethio[grepl("^NOT",x$dst_ethio,ignore.case=TRUE)] <- 2
x$dst_ethio[grepl("^UNK",x$dst_ethio,ignore.case=TRUE)] <- 9

x$dst_pas[grepl("^NA",x$dst_pas,ignore.case=TRUE)] <- ""
x$dst_pas[grepl("^SEN",x$dst_pas,ignore.case=TRUE)] <- 0
x$dst_pas[grepl("^RES",x$dst_pas,ignore.case=TRUE)] <- 1
x$dst_pas[grepl("^NOT",x$dst_pas,ignore.case=TRUE)] <- 2
x$dst_pas[grepl("^UNK",x$dst_pas,ignore.case=TRUE)] <- 9

x$dst_clf[grepl("^NA",x$dst_clf,ignore.case=TRUE)] <- ""
x$dst_clf[grepl("^SEN",x$dst_clf,ignore.case=TRUE)] <- 0
x$dst_clf[grepl("^RES",x$dst_clf,ignore.case=TRUE)] <- 1
x$dst_clf[grepl("^NOT",x$dst_clf,ignore.case=TRUE)] <- 2
x$dst_clf[grepl("^UNK",x$dst_clf,ignore.case=TRUE)] <- 9

x$smear_conv[x$smear_conv=="HALF-MONTH"]<-1
x$smear_conv[x$smear_conv=="NA"]<-99


x$end_rx_smear[grepl("^NA",x$end_rx_smear,ignore.case=TRUE)] <- ""
x$end_rx_smear[grepl("^U",x$end_rx_smear,ignore.case=TRUE)] <-9
x$end_rx_smear[grepl("^NOT",x$end_rx_smear,ignore.case=TRUE)] <- 2
x$end_rx_smear[grepl("^NEG",x$end_rx_smear,ignore.case=TRUE)] <- 0
x$end_rx_smear[grepl("^POS",x$end_rx_smear,ignore.case=TRUE)] <- 1


x$rx_outcome[grepl("^NA",x$rx_outcome,ignore.case=TRUE)] <- ""
x$rx_outcome[grepl("^CU",x$rx_outcome,ignore.case=TRUE)] <- 1
x$rx_outcome[grepl("^CO",x$rx_outcome,ignore.case=TRUE)] <- 2
x$rx_outcome[grepl("^F",x$rx_outcome,ignore.case=TRUE)] <- 3
x$rx_outcome[grepl("^D",x$rx_outcome,ignore.case=TRUE)] <- 4
x$rx_outcome[grepl("^L",x$rx_outcome,ignore.case=TRUE)] <- 5
```

```{r complete}
x$main_database_demographics_complete<-2
x$main_database_tbinvestigation_complete<-2
x$active_tb_tbinvestigation_complete<-2
x$tst_reactive_treatment_complete<-2
```

```{r reactive TB}
x$prev_therapy[grepl("NA",x$prev_therapy,ignore.case=TRUE)]<-""
x$prev_therapy[grepl("RECE",x$prev_therapy,ignore.case=TRUE)]<-1
x$prev_therapy[grepl("^NOT RECE",x$prev_therapy,ignore.case=TRUE)]<-2
x$prev_therapy[grepl("^C",x$prev_therapy,ignore.case=TRUE)]<-3
x$prev_therapy[grepl("^NOT RE",x$prev_therapy,ignore.case=TRUE)]<-5
x$prev_therapy[grepl("^A",x$prev_therapy,ignore.case=TRUE)]<-6
x$prev_therapy[grepl("^TB",x$prev_therapy,ignore.case=TRUE)]<-6

x$prev_therapy_reg[grepl("NA",x$prev_therapy_reg,ignore.case=TRUE)]<-""
x$prev_therapy_reg[grepl("4R",x$prev_therapy_reg,ignore.case=TRUE)]<-1
x$prev_therapy_reg[grepl("3HR",x$prev_therapy_reg,ignore.case=TRUE)]<-2
x$prev_therapy_reg[grepl("6H",x$prev_therapy_reg,ignore.case=TRUE)]<-3
x$prev_therapy_reg[grepl("3HP",x$prev_therapy_reg,ignore.case=TRUE)]<-4
x$prev_therapy_reg[grepl("NA",x$prev_therapy_reg,ignore.case=TRUE)]<-99

x$prevther_adr[grepl("NA",x$prevther_adr,ignore.case=TRUE)]<-99
x$prevther_adr[grepl("^N",x$prevther_adr,ignore.case=TRUE)]<-0
x$prevther_adr[grepl("^Y",x$prevther_adr,ignore.case=TRUE)]<-1

x$culprit_drug[grepl("NA",x$culprit_drug ,ignore.case=TRUE)]<-99
x$culprit_drug[grepl("Rif",x$culprit_drug,ignore.case=TRUE)]<-1
x$culprit_drug[grepl("^I",x$culprit_drug,ignore.case=TRUE)]<-2
x$culprit_drug[grepl("Rif-Inh",x$culprit_drug,ignore.case=TRUE)]<-3

x$totalbil_1[grepl("NA",x$totalbil_1 ,ignore.case=TRUE)]<-""
x$directl_1[grepl("NA",x$directl_1,ignore.case=TRUE)]<-""
x$sgpt_1[grepl("NA",x$sgpt_1,ignore.case=TRUE)]<-""
x$sgot_1[grepl("NA",x$sgot_1,ignore.case=TRUE)]<-""
x$totalbil_2[grepl("NA",x$totalbil_2,ignore.case=TRUE)]<-""
x$directbil_2[grepl("NA", x$directbil_2,ignore.case=TRUE)]<-""
x$sgpt_2[grepl("NA",x$sgpt_2,ignore.case=TRUE)]<-""
x$sgot_2[grepl( "NA",x$sgot_2,ignore.case=TRUE)]<-""
x$totalbil_3[grepl("NA",x$totalbil_3,ignore.case=TRUE)]<-""
x$directbil_3[grepl("NA",x$directbil_3,ignore.case=TRUE)]<-""
x$sgpt_3[grepl("NA",x$sgpt_3,ignore.case=TRUE)]<-""
x$sgot_3[grepl("NA",x$sgot_3,ignore.case=TRUE)]<-""
x$totalbil_4[grepl("NA",x$totalbil_4,ignore.case=TRUE)]<-""
x$directbil_4[grepl("NA",x$directbil_4,ignore.case=TRUE)]<-""
x$sgpt_4[grepl("NA",x$sgpt_4,ignore.case=TRUE)]<-""
x$sgot_4[grepl("NA",x$sgot_4,ignore.case=TRUE)]<-"" 

x$prevtherapy_held[grepl("NA",x$prevtherapy_held,ignore.case=TRUE)]<-99
x$prevtherapy_held[grepl("^N",x$prevtherapy_held,ignore.case=TRUE)]<-0
x$prevtherapy_held[grepl("^Y",x$prevtherapy_held,ignore.case=TRUE)]<-1

x$prev_therapy_revised[grepl("NA",x$prev_therapy_revised,ignore.case=TRUE)]<-99
x$prev_therapy_revised[grepl("^N",x$prev_therapy_revised,ignore.case=TRUE)]<-0
x$prev_therapy_revised[grepl("^Y",x$prev_therapy_revised,ignore.case=TRUE)]<-1

x$revised_prevther_reg[grepl("NA",x$revised_prevther_reg,ignore.case=TRUE)]<-""
x$revised_prevther_reg[grepl("^4",x$revised_prevther_reg,ignore.case=TRUE)]<-1
x$revised_prevther_reg[grepl("^3HR",x$revised_prevther_reg,ignore.case=TRUE)]<-2
x$revised_prevther_reg[grepl("^6",x$revised_prevther_reg,ignore.case=TRUE)]<-3
x$revised_prevther_reg[grepl("^3HP",x$revised_prevther_reg,ignore.case=TRUE)]<-4
x$revised_prevther_reg[!grepl("^4|^3HR|^6|^3HP|^NA", x$revised_prevther_reg,ignore.case=TRUE)]<- ""

x$prevther_outcome[grepl("NA",x$prevther_outcome,ignore.case=TRUE)]<-""
x$prevther_outcome[grepl("^COM",x$prevther_outcome,ignore.case=TRUE)]<-1
x$prevther_outcome[grepl("^L",x$prevther_outcome,ignore.case=TRUE)]<-2
x$prevther_outcome[grepl("^A",x$prevther_outcome,ignore.case=TRUE)]<-3
x$prevther_outcome[grepl("TB",x$prevther_outcome,ignore.case=TRUE)]<-3
x$prevther_outcome[!grepl("NA|^COM|^L|^A|TB", x$prevther_outcome,ignore.case=TRUE)]<- 4

x$prevther_stopped_premature[grepl("NA",x$prevther_stopped_premature,ignore.case=TRUE)]<-99
x$prevther_stopped_premature[grepl("^N",x$prevther_stopped_premature,ignore.case=TRUE)]<-0
x$prevther_stopped_premature[grepl("^Y",x$prevther_stopped_premature,ignore.case=TRUE)]<-1

x$prevther_stopped_reason[grepl("NA",x$prevther_stopped_reason,ignore.case=TRUE)]<-""
x$prevther_stopped_reason[grepl("^H",x$prevther_stopped_reason,ignore.case=TRUE)]<- 1
x$prevther_stopped_reason[grepl("^other tox",x$prevther_stopped_reason,ignore.case=TRUE)]<- 2
x$prevther_stopped_reason[grepl("^discont",x$prevther_stopped_reason,ignore.case=TRUE)]<- 3
x$prevther_stopped_reason[!grepl("NA|^H|^other tox|^discont", x$prevther_stopped_reason,ignore.case=TRUE)]<- 4

x$tst_reactive_treatment_complete[x$tst_reactive_treatment_complete=="INCOMPLETE"]<-0
x$tst_reactive_treatment_complete[x$tst_reactive_treatment_complete=="UNVERIFIED"]<-1
x$tst_reactive_treatment_complete[x$tst_reactive_treatment_complete=="COMPLETE"]<-2


```

```{r dates}
x$prevther_startdate[grepl("NA",x$prevther_startdate,ignore.case=TRUE)]<-""
x$date_prevther_held[grepl("NA",x$date_prevther_held,ignore.case=TRUE)]<-""
x$date_prevther_restarted[grepl("NA",x$date_prevther_restarted,ignore.case=TRUE)]<-""
x$date_rx_start = mdy(x$date_rx_start)
x$date_rx_stopped = mdy(x$date_rx_stopped)
```

```{r complete}
x$main_database_demographics_complete<-2
x$main_database_tbinvestigation_complete<-2
x$active_tb_tbinvestigation_complete<-2
x$tst_reactive_treatment_complete<-2
```


```{r export}
write.csv(x,"C:/Users/g_pun/Dropbox/ZeroTB/GTCV/ACF_2018_clean.csv", na="")
```




















