---
title: "code"
author: "Gopika Punchhi"
date: "7/23/2019"
output: html_document
---

```{r institute, include=FALSE}

library(plyr)
library(readr)
library(dplyr)
library(tidyverse)
library(readxl)

setwd(C:/ZeroTB)
getwd()
x=read_excel("/GTCV 2018_CONTACT_TRACE.xl")

##Insitute variable renaming
x=read.csv()
x$institute[x$institute==]<-1
x$institute[x$institute==]<-2
x$institute[x$institute=="GTCV"]<-3
x$institute[x$institute==GTCV]<-4
x$institute[x$institute==GTCV]<-5
x$institute[x$institute==GTCV]<-6
x$institute[x$institute==GTCV]<-7
x$institute[x$institute==GTCV]<-8
x$institute[x$institute==GTCV]<-9
x$institute[x$institute==GTCV]<-10
x$institute[x$institute==GTCV]<-11
x$institute[x$institute==GTCV]<-12
x$institute[x$institute==GTCV]<-13
x$institute[x$institute==GTCV]<-14
x$institute[x$institute==GTCV]<-15
x$institute[x$institute==GTCV]<-16
x$institute[x$institute==GTCV]<-17
x$institute[x$institute==GTCV]<-18
```

```{r sex}
x$sex[x$sex=="MALE"]<-1
x$sex[x$sex=="M"]<-1
x$sex[x$sex=="male"]<-1
x$sex[x$sex=="m"]<-1

x$sex[x$sex=="FEMALE"]<-2
x$sex[x$sex=="F"]<-2
x$sex[x$sex=="female"]<-2
x$sex[x$sex=="f"]<-2

```

```{r dorm}
x$dorm[x$dorm="H-1"]->1
x$dorm[x$dorm="H-2"]->1
x$dorm[x$dorm="H-3"]->1
x$dorm[x$dorm="H-4"]->1
x$dorm[x$dorm="H-5"]->1
x$dorm[x$dorm="H-6"]->1
x$dorm[x$dorm="H-7"]->1
x$dorm[x$dorm="H-8"]->1
x$dorm[x$dorm="H-9"]->1
x$dorm[x$dorm="H-10"]->1
x$dorm[x$dorm="H-11"]->1
x$dorm[x$dorm="H-12"]->1
x$dorm[x$dorm="H-13"]->1
x$dorm[x$dorm="H-14"]->1
x$dorm[x$dorm="H-15"]->1
x$dorm[x$dorm="H-16"]->1
x$dorm[x$dorm="H-17"]->1
x$dorm[x$dorm="H-18"]->1
x$dorm[x$dorm="H-19"]->1
x$dorm[x$dorm="H-20"]->1
x$dorm[x$dorm="H-21"]->1
x$dorm[x$dorm="H-22"]->1
x$dorm[x$dorm="H-23"]->1
x$dorm[x$dorm="H-24"]->1
x$dorm[x$dorm="H-25"]->1
x$dorm[x$dorm="H-26"]->1
x$dorm[x$dorm="H-27"]->1
x$dorm[x$dorm="H-28"]->1
x$dorm[x$dorm="H-29"]->1
x$dorm[x$dorm="H-30"]->1
x$dorm[x$dorm="H-31"]->1
x$dorm[x$dorm="H-32"]->1
x$dorm[x$dorm="H-33"]->1
x$dorm[x$dorm="H-34"]->1
x$dorm[x$dorm="H-35"]->1
x$dorm[x$dorm="H-36"]->1
x$dorm[x$dorm="H-37"]->1
x$dorm[x$dorm="H-38"]->1
x$dorm[x$dorm="H-39"]->1
x$dorm[x$dorm="H-40"]->1
x$dorm[x$dorm="H-41"]->1
x$dorm[x$dorm="H-42"]->1
x$dorm[x$dorm="H-43"]->1
x$dorm[x$dorm="H-44"]->1
x$dorm[x$dorm="H-45"]->1
x$dorm[x$dorm="H-46"]->1
x$dorm[x$dorm="H-47"]->1
x$dorm[x$dorm="H-48"]->1
x$dorm[x$dorm="H-48"]->1
x$dorm[x$dorm="H-50"]->1
x$dorm[x$dorm=="BH"]->2
x$dorm[x$dorm=="GH"]->3
x$dorm[x$dorm=="DS"]->4
x$dorm[x$dorm=="SQ"]->5
```

```{r occuapation}
x$occupation[x$occupation=="STUDENT"]->1
x$occupation[x$occupation=="TEACHER"]->2
x$occupation[x$occupation=="HEALTH-STAFF"]->3
x$occupation[x$occupation=="OFFICE-STAFF"]->4
x$occupation[x$occupation=="HOME-MOTHER"]->5
x$occupation[x$occupation=="MONK"]->6
x$occupation[x$occupation=="NUN"]->7
x$occupation[x$occupation=="COOK"]->8
x$occupation[x$occupation=="DRIVER"]->9
x$occupation[x$occupation=="HOME-FATHER"]->10
```

```{ country}
if (x$birth_place==("INDIA","TIBET","NEPAL","BHUTAN")) {
x$birth_place[x$birth_place=="INDIA"]->1
  x$birth_place[x$birth_place=="TIBET"]->2
  x$birth_place[x$birth_place=="NEPAL"]->3
  x$birth_place[x$birth_place=="BHUTAN"]->4
} else { replace( how to replace all other here)
```

```{r prev tb}
x$prev_tb[x$prev_tb=="NO"]->0
x$prev_tb[x$prev_tb=="YES"]->1
x$prev_tb[x$prev_tb=="NA"]->NA

```

```{r prev tb type}
x$prevtb_type[x$prevtb_type=="NON MDR"]->0
x$prevtb_type[x$prevtb_type=="MDR"]->1
x$x$prevtb_type[x$prevtb_type=="NA"]->NA

```

```{r seizures}
x$seizures[x$seizures=="NO"]->0
x$seizures[x$seizures=="YES"]->1
```

```{r hepb}
x$hepb[x$hepb=="NO"]->0
x$hepb[x$hepb=="YES"]->1
```

```{r preg_breastfeed}
x$preg_breastfeed[x$preg_breastfeed=="NO"]->0
x$preg_breastfeed[x$preg_breastfeed=="PREG"]->1
x$preg_breastfeed[x$preg_breastfeed=="BREASTFEED"]->2
```

```{r other comorbid}
x$other_comorbid[x$other_comorbid=="NONE"]->0
x$other_comorbid[x$other_comorbid=="DM"]->1
x$other_comorbid[x$other_comorbid=="HTN"]->2
x$other_comorbid[x$other_comorbid=="DM_HTN"]->3
x$other_comorbid[x$other_comorbid=="OTHER"]->4
```

```{r longterm med}
x$longterm_med[x$longmterm_med=="NONE"]->0
x$longterm_med[x$longmterm_med=="ANTI-HEPB"]->1
x$longterm_med[x$longmterm_med=="ANTI_SEIZURE"]->2
x$longterm_med[x$longmterm_med=="ANTI_DM"]->3
x$longterm_med[x$longmterm_med=="ANTI-HTN"]->4
x$longterm_med[x$longmterm_med=="ANTI-DMHTN"]->5
x$longterm_med[x$longmterm_med=="ANTI-HEPBDM"]->6
x$longterm_med[x$longmterm_med=="ANTI-HEPHTN"]->7
x$longterm_med[x$longmterm_med=="ANTI-HEPBSEIZURE"]->8
x$longterm_med[x$longmterm_med=="ANTI-SEIZUREDM"]->9
x$longterm_med[x$longmterm_med=="ANTI_SEIZUREHTN"]->10
x$longterm_med[x$longmterm_med=="OTHER"]->11
```

```{r eversmoked}
x$ever_smoked[x$ever_smoked=="NO"]->0
x$ever_smoked[x$ever_smoked=="YES"]->1
```

```{r bcg tibetborn}
x$bcg_tibetborn[x$bcg_tibetborn=="NO"]->0
x$bcg_tibetborn[x$bcg_tibetborn=="YES"]->1
```

```{r contact with TB in last two years}
x$contactsch_2yr[x$contactsch_2yr=="NO"]->0
x$contactsch_2yr[x$contactsch_2yr=="YES"]->1
x$contactsch_2yr[x$contactsch_2yr=="UNKNOWN"]->2
```

```{r drug sensitivity of Tb case at school}
x$indexcasesch_tbtype[x$indexcasesch_tbtype=="NON MDR"]->0
x$indexcasesch_tbtype[x$indexcasesch_tbtype=="MDR"]->1
```

```{r index case at school}
x$indexcasesch_is[x$indexcasesch_is=="CLASS MATE"]->1
x$indexcasesch_is[x$indexcasesch_is=="DORM MATE"]->2
x$indexcasesch_is[x$indexcasesch_is=="CLASSDORM MATE"]->3
x$indexcasesch_is[x$indexcasesch_is=="SCHOOL STAFF"]->4
x$indexcasesch_is[x$indexcasesch_is=="FRIEND"]->5
x$indexcasesch_is[x$indexcasesch_is=="OTHER"]->6
```

```{r exposed to TB athome}
x$contacthome_2yr[x$contacthome_2yr=="NO"]->0
x$contacthome_2yr[x$contacthome_2yr=="YES"]->1
x$contacthome_2yr[x$contacthome_2yr=="UNKNOWN"]->2
```

```{r drug sensitivity of the TB case at home}
x$indexcasehome_tbtype[x$indexcasehome_tbtype=="NON MDR"]->0
x$indexcasehome_tbtype[x$indexcasehome_tbtype=="MDR"]->1
```

```{r index case at home}













