---
title: "tst reactive"
author: "Gopika Punchhi"
date: "8/13/2019"
output: html_document
---
```{r institute, include=FALSE}

library(plyr)
library(readr)
library(dplyr)
library(tidyverse)


x=read.csv("C:/Users/g_pun/Dropbox/####", stringsAsFactors = FALSE, na.strings=TRUE)
```

```{r institute}
x$institute_reactivetb[x$institute_reactivetb==""]<-
```

```{r sex}
x$sex_reactivetb[x$sex_reactivetb=="M"]<-1
x$sex_reactivetb[x$sex_reactivetb=="MALE"]<-1
x$sex_reactivetb[x$sex_reactivetb=="m"]<-1
x$sex_reactivetb[x$sex_reactivetb=="F"]<-2
x$sex_reactivetb[x$sex_reactivetb=="FEMALE"]<-2
x$sex_reactivetb[x$sex_reactivetb=="f"]<-2
```

```{r dorm}
x$dorm_reactivetb[!grepl("^B|^H|^G",x$dorm_reactivetb,ignore.case=TRUE)] <- ""
x$dorm_reactivetb[grepl("^H",x$dorm_reactivetb,ignore.case=TRUE)] <- 1
x$dorm_reactivetb[grepl("^G",x$dorm_reactivetb,ignore.case=TRUE)] <- 3
x$dorm_reactivetb[grepl("^B",x$dorm_reactivetb,ignore.case=TRUE)] <- 2
```

```{r occuapation}
x$occupation_reactivetb[x$occupation_reactivetb=="STUDENT"]<-1
x$occupation_reactivetb[x$occupation_reactivetb=="TEACHER"]<-2
x$occupation_reactivetb[x$occupation_reactivetb=="HEALTH-STAFF"]<-3
x$occupation_reactivetb[x$occupation_reactivetb=="OFFICE-STAFF"]<-4
x$occupation_reactivetb[x$occupation_reactivetb=="HOME-MOTHER"]<-5
x$occupation_reactivetb[x$occupation_reactivetb=="MONK"]<-6
x$occupation_reactivetb[x$occupation_reactivetb=="NUN"]<-7
x$occupation_reactivetb[x$occupation_reactivetb=="COOK"]<-8
x$occupation_reactivetb[x$occupation_reactivetb=="DRIVER"]<-9
x$occupation_reactivetb[x$occupation_reactivetb=="HOME-FATHER"]<-10
x$occupation_reactivetb[x$occupation_reactivetb=="STAFF"]<-""
```

```{r Country}
x$birth_place_reactivetb[!grepl("^IND|^TIB|^NEP|^BHU", x$birth_place_reactivetb,ignore.case=TRUE)] <- 5
x$birth_place_reactivetb[x$birth_place_reactivetb=="INDIA"]<-1
x$birth_place_reactivetb[x$birth_place_reactivetb=="TIBET"]<-2
x$birth_place_reactivetb[x$birth_place_reactivetb=="NEPAL"]<-3
x$birth_place_reactivetb[x$birth_place_reactivetb=="BHUTAN"]<-4
```

```{r complete demo}
x$tst_reactive_demographics_complete[x$tst_reactive_demographics_complete=="INCOMPLETE"]<-0
x$tst_reactive_demographics_complete[x$tst_reactive_demographics_complete=="UNVERIFIED"]<-1
x$tst_reactive_demographics_complete[x$tst_reactive_demographics_complete=="COMPLETE"]<-2
```


```{r prev therapy}
x$prev_therapy[x$prev_therapy=="RECEIVED"]<-1
x$prev_therapy[x$prev_therapy=="NOT RECEIVED"]<-2
x$prev_therapy[x$prev_therapy=="CONSENTED"]<-3
x$prev_therapy[x$prev_therapy=="REFUSED"]<-4
x$prev_therapy[x$prev_therapy=="NOT RECOMMENDED"]<-5
x$prev_therapy[x$prev_therapy=="ACTIVE TB"]<-6
```

```{r prev regimen}
x$prev_therapy_reg[x$prev_therapy_reg="4R"]<-1
x$prev_therapy_reg[x$prev_therapy_reg="3HR"]<-2
x$prev_therapy_reg[x$prev_therapy_reg="6H"]<-3
x$prev_therapy_reg[x$prev_therapy_reg="3HP"]<-4
```

```{r adverse reaction}
x$prevther_adr[x$prevther_adr=="NO"]<-0
x$prevther_adr[x$prevther_adr=="YES"]<-1
```


```{r culprit drug}
x$culprit_drug[x$cu

```

```{r seizures}
x$seizures[x$seizures=="NO"]<-0
x$seizures[x$seizures=="YES"]<-1
```

```{r hepb}
x$hepb[x$hepb=="NO"]<-0
x$hepb[x$hepb=="YES"]<-1
```

```{r preg_breastfeed}
x$preg_breastfeed[x$preg_breastfeed=="NO"]<-0
x$preg_breastfeed[x$preg_breastfeed=="PREG"]<-1
x$preg_breastfeed[x$preg_breastfeed=="BREASTFEED"]<-2
```

```{r other comorbid}
x$other_cormorbid[x$other_cormorbid=="NONE"]<-0
x$other_cormorbid[x$other_cormorbid=="DM"]<-1
x$other_cormorbid[x$other_cormorbid=="HTN"]<-2
x$other_cormorbid[x$other_cormorbid=="DM_HTN"]<-3
x$other_cormorbid[x$other_cormorbid=="OTHER"]<-4
```

```{r longterm med}
x$longterm_med[x$longterm_med=="NONE"]<-0
x$longterm_med[x$longterm_med=="ANTI-HEPB"]<-1
x$longterm_med[x$longterm_med=="ANTI_SEIZURE"]<-2
x$longterm_med[x$longterm_med=="ANTI_DM"]<-3
x$longterm_med[x$longterm_med=="ANTI-HTN"]<-4
x$longterm_med[x$longterm_med=="ANTI-DMHTN"]<-5
x$longterm_med[x$longterm_med=="ANTI-HEPBDM"]<-6
x$longterm_med[x$longterm_med=="ANTI-HEPHTN"]<-7
x$longterm_med[x$longterm_med=="ANTI-HEPBSEIZURE"]<-8
x$longterm_med[x$longterm_med=="ANTI-SEIZUREDM"]<-9
x$longterm_med[x$longterm_med=="ANTI_SEIZUREHTN"]<-10
x$longterm_med[x$longterm_med=="OTHER"]<-11
```

```{r eversmoked}
x$ever_smoked[x$ever_smoked=="NO"]<-0
x$ever_smoked[x$ever_smoked=="YES"]<-1
```

```{r bcg tibetborn}
x$bcg_tibetborn[x$bcg_tibetborn=="NO"]<-0
x$bcg_tibetborn[x$bcg_tibetborn=="YES"]<-1
```

```{r contact with TB in last two years}
x$contactsch_2yr[x$contactsch_2yr=="NO"]<-0
x$contactsch_2yr[x$contactsch_2yr=="YES"]<-1
x$contactsch_2yr[x$contactsch_2yr=="UNKNOWN"]<-2
```

```{r drug sensitivity of Tb case at school}
x$indexcasesch_tbtype[x$indexcasesch_tbtype=="NON MDR"]<-0
x$indexcasesch_tbtype[x$indexcasesch_tbtype=="MDR"]<-1
x$indexcasesch_tbtype[x$indexcasesch_tbtype==""]<-9
x$indexcasesch_tbtype[x$indexcasesch_tbtype=="NA"]<-""

```

```{r index case at school}
x$indexcasesch_is[x$indexcasesch_is=="CLASS MATE"]<-1
x$indexcasesch_is[x$indexcasesch_is=="CLASSMATE"]<-1
x$indexcasesch_is[x$indexcasesch_is=="DORM MATE"]<-2
x$indexcasesch_is[x$indexcasesch_is=="CLASSDORM MATE"]<-3
x$indexcasesch_is[x$indexcasesch_is=="SCHOOL STAFF"]<-4
x$indexcasesch_is[x$indexcasesch_is=="FRIEND"]<-5
x$indexcasesch_is[x$indexcasesch_is=="OTHER"]<-6
x$indexcasesch_is[x$indexcasesch_is=="NA"]<-""

```

```{r exposed to TB athome}
x$contacthome_2yr[x$contacthome_2yr=="NO"]<-0
x$contacthome_2yr[x$contacthome_2yr=="YES"]<-1
x$contacthome_2yr[x$contacthome_2yr=="UNKNOWN"]<-2


```

```{r drug sensitivity of the TB case at home}
x$indexcasehome_tbtype[x$indexcasehome_tbtype=="NON MDR"]<-0
x$indexcasehome_tbtype[x$indexcasehome_tbtype=="MDR"]<-1
```

```{r index case at home}
x$indexcasehome_is[x$indexcasehome_is=="PARENT"]<-1
x$indexcasehome_is[x$indexcasehome_is=="SIBLING"]<-2
x$indexcasehome_is[x$indexcasehome_is=="GRANDPARENT"]<-3
x$indexcasehome_is[x$indexcasehome_is=="OTHER"]<-4
x$indexcasehome_is[x$indexcasehome_is=="NA"]<-""
```

```{r indexcasehome_count}
x$indexcasehome_count[x$indexcasehome_count=="0"]<-0
x$indexcasehome_count[x$indexcasehome_count=="1"]<-1
x$indexcasehome_count[x$indexcasehome_count=="2"]<-2
x$indexcasehome_count[x$indexcasehome_count>="3"]<-3
#### CHECK THIS LAST LINE OF CODE
```

```{r presence of cough}
x$cough[x$cough=="NO"]<-0
x$cough[x$cough=="YES"]<-1
```


```{r cough duration in weeks}
x$coughduration_wks[x$coughduration_wks=="LT-ONE"]<-1
x$coughduration_wks[x$coughduration_wks=="ONE-TWO"]<-2
x$coughduration_wks[x$coughduration_wks=="TWO-THREE"]<-3
x$coughduration_wks[x$coughduration_wks=="THREE"]<-4
x$coughduration_wks[x$coughduration_wks=="GE-THREE"]<-4
x$coughduration_wks[x$coughduration_wks=="NA"]<-""

```

```{r patient cough productive}
x$productive_cough[x$productive_cough=="NO"]<-
x$productive_cough[x$productive_cough=="YES"]<-1
x$productive_cough[x$productive_cough=="NA"]<-""
```

```{r presence of blood in sputum}
x$blood_sputum[x$blood_sputum=="NO"]<-0
x$blood_sputum[x$blood_sputum=="YES"]<-1
x$blood_sputum[x$blood_sputum=="NA"]<-""
```

```{r fever}
x$fever[x$fever=="NO"]<-0
x$fever[x$fever=="YES"]<-1
```

```{r fever duration}
x$fever_duration[x$fever_duration=="LT-ONE"]<-1
x$fever_duration[x$fever_duration=="ONE-TWO"]<-2
x$fever_duration[x$fever_duration=="GE-TWO"]<-3
x$fever_duration[x$fever_duration=="TWO"]<-3
x$fever_duration[x$fever_duration=="NA"]<-4
```

```{r presence of night sweats}
x$nightsweats_2wks[x$nightsweats_2wks=="NO"]<-0
x$nightsweats_2wks[x$nightsweats_2wks=="YES"]<-1
```

```{r weight loss in year prior}
x$wtloss_1month[x$wtloss_1month=="NO"]<-0
x$wtloss_1month[x$wtloss_1month=="YES"]<-1
```

```{r fatigue prior 2 weeks}
x$fatigue_last2wks[x$fatigue_last2wks=="NO"]<-0
x$fatigue_last2wks[x$fatigue_last2wks=="YES"]<-1
```

```{r ongoing chest pain}
x$chestpain_current[x$chestpain_current=="NO"]<-0
x$chestpain_current[x$chestpain_current=="YES"]<-1
```


```{r previous tst done}
x$tst1_done[x$tst1_done=="YES"]<-1
x$tst1_done[x$tst1_done=="PREV TB"]<-2
x$tst1_done[x$tst1_done=="PREVTB"]<-2
x$tst1_done[x$tst1_done=="NOT INDICATED"]<-3
x$tst1_done[x$tst1_done=="NOTINDICATED"]<-3
x$tst1_done[x$tst1_done=="REFUSED"]<-4
```

```{r wheal size}
x$wheal1_size[x$wheal1_size=="NA"]<-""
```

```{r date}
x$xpert1_date[x$xpert1_date=="NA"]<-""
```

```{r type of specimen xpert}
x$xpert1_specimen[x$xpert1_specimen=="SPUTUM"]<-1
x$xpert1_specimen[x$xpert1_specimen=="GA"]<-2
x$xpert1_specimen[x$xpert1_specimen=="PUS"]<-3
x$xpert1_specimen[x$xpert1_specimen=="PLEURAL FLUID"]<-4
x$xpert1_specimen[x$xpert1_specimen=="URINE"]<-5
x$xpert1_specimen[x$xpert1_specimen=="CSF"]<-6
x$xpert1_specimen[x$xpert1_specimen=="NA"]<-""
```

```{r result of xpert analysis}
x$xpert1_result[x$xpert1_result=="NOT DETECTED"]<-0
x$xpert1_result[x$xpert1_result=="DETECTED"]<-1
x$xpert1_result[x$xpert1_result=="NA"]<-""
```

```{r drug sensitivty as per xpert analysis}
x$xpert1_mtb[x$xpert1_mtb=="VL"]<-0
x$xpert1_mtb[x$xpert1_mtb=="LOW"]<-1
x$xpert1_mtb[x$xpert1_mtb=="MED"]<-2
x$xpert1_mtb[x$xpert1_mtb=="HIGH"]<-3
x$xpert1_mtb[x$xpert1_mtb=="NA"]<-""

```

```{r rifampin resistance}
x$xpert1_rif[x$xpert1_rif=="SEN"]<-0
x$xpert1_rif[x$xpert1_rif=="RES"]<-1
x$xpert1_rif[x$xpert1_rif=="INDET"]<-2
x$xpert1_rif[x$xpert1_rif=="NA"]<-""
```

```{r xpert2 date}
x$xpert2_date[x$xpert2_date=="NA"]<-""
```

```{r type of spec use for 2nd xpert}
x$xpert2_specimen[x$xpert2_specimen=="SPUTUM"]<-1
x$xpert2_specimen[x$xpert2_specimen=="GA"]<-2
x$xpert2_specimen[x$xpert2_specimen=="PUS"]<-3
x$xpert2_specimen[x$xpert2_specimen=="PLEURAL FLUID"]<-4
x$xpert2_specimen[x$xpert2_specimen=="URINE"]<-5
x$xpert2_specimen[x$xpert2_specimen=="CSF"]<-6
x$xpert2_specimen[x$xpert2_specimen=="NA"]<-""
```

```{r result of xpert2}
x$xpert2_specimen[x$xpert2_specimen=="NOT DETECTED"]<-0
x$xpert2_specimen[x$xpert2_specimen=="DETECTED"]<-1
x$xpert2_specimen[x$xpert2_specimen=="NA"]<-""
```

```{r xpert2 result}
x$xpert2_result[x$xpert2_result=="NA"]<-""
```


```{r drug sensitivty as per xpert2 analysis}
x$xpert2_mtb[x$xpert2_mtb=="VL"]<-0
x$xpert2_mtb[x$xpert2_mtb=="LOW"]<-1
x$xpert2_mtb[x$xpert2_mtb=="MED"]<-2
x$xpert2_mtb[x$xpert2_mtb=="HIGH"]<-3
x$xpert2_mtb[x$xpert2_mtb=="NA"]<-""
```

```{r rifampin resistance 2}
x$xpert2_rif[x$xpert2_rif=="SEN"]<-0
x$xpert2_rif[x$xpert2_rif=="RES"]<-1
x$xpert2_rif[x$xpert2_rif=="INDET"]<-2
x$xpert2_rif[x$xpert2_rif=="NA"]<-""

```

```{r cxr}
x$cxr[x$cxr=="NO"]<-0
x$cxr[x$cxr=="YES"]<-1
x$cxr[x$cxr=="NA"]<-""
```

```{r cxr result}
x$cxr_result[x$cxr_result=="NORMAL"]<-0
x$cxr_result[x$cxr_result=="ABNORMAL"]<-1
x$cxr_result[x$cxr_result=="NA"]<-""
```

```{r diagnosed with active TB}
x$tb_diagnosed[x$tb_diagnosed=="NO"]<-0
x$tb_diagnosed[x$tb_diagnosed=="YES"]<-1
x$tb_diagnosed[x$tb_diagnosed=="NA"]<-""

```

```{r total num of students}
x$total_students[x$total_students=="NA"]<-""
```

```{r total staff}
x$total_monks_nuns[x$total_monks_nuns=="NA"]<-""
```

```{r notes main}
x$notes_main[x$notes_main=="NA"]<-""
```

```{r demographics}
x$main_database_demographics_complete<-2
x$main_database_tbinvestigation_complete<-2
x$active_tb_demographics_complete<-2
x$active_tb_tbinvestigation_complete<-2
x$tst_reactive_demographics_complete<-2
x$tst_reactive_treatment_complete<-2

```


```{r export}
write.csv(x,"C:/Users/g_pun/Dropbox/ZeroTB/####", na="")
```
















