---
title: "TST Reactive"
author: "Anisha Nagpal"
date: "July 29, 2019"
output: html_document
---

```{r download, include=FALSE}
library(plyr)
library(readr)
library(dplyr)
library(tidyverse)
library(lubridate)

x<-read.csv("C:/Users/anish/Documents/Zero TB in Kids/GCTV 2018 TST_REAC.csv", stringsAsFactors=FALSE, na.strings=TRUE)
```

```{r Reactive TB Institute}
x$institute_activetb[x$institute_activetb=="GTCV"]<-3
x$institute_activetb[x$institute_activetb=="LTCV"]<-1
x$institute_reactivetb[x$institute_reactivetb=="GTCV"]<-3
x$institute_reactivetb[x$institute_reactivetb=="LTCV"]<-1
```


```{r Reactive TB Sex}
x$sex_reactivetb[x$sex_activetb=="MALE"]<-1
x$sex_reactivetb[x$sex_activetb=="M"]<-1
x$sex_reactivetb[x$sex_activetb=="male"]<-1
x$sex_reactivetb[x$sex_activetb=="m"]<-1
x$sex_reactivetb[x$sex_activetb=="FEMALE"]<-2
x$sex_reactivetb[x$sex_activetb=="F"]<-2
x$sex_reactivetb[x$sex_activetb=="female"]<-2
x$sex_reactivetb[x$sex_activetb=="f"]<-2

```

```{r Reactive TB Dorm}

x$dorm_reactivetb[!grepl("^B|^H|^G",x$dorm_reactivetb,ignore.case=TRUE)] <- ""
x$dorm_reactivetb[grepl("^H",x$dorm_reactivetb,ignore.case=TRUE)] <- 1
x$dorm_reactivetb[grepl("^G",x$dorm_reactivetb,ignore.case=TRUE)] <- 3
x$dorm_reactivetb[grepl("^B",x$dorm_reactivetb,ignore.case=TRUE)] <- 2
```

```{r Reactive TB Occupation}
x$occupation_reactivetb[grepl("^STU",x$occupation_reactivetb,ignore.case=TRUE)] <- 1
x$occupation_reactivetb[grepl("^TEA",x$occupation_reactivetb,ignore.case=TRUE)] <- 2
x$occupation_reactivetb[grepl("^HEAL",x$occupation_reactivetb,ignore.case=TRUE)] <- 3
x$occupation_reactivetb[grepl("^OFF",x$occupation_reactivetb,ignore.case=TRUE)] <- 4
x$occupation_reactivetb[grepl("^MON",x$occupation_reactivetb,ignore.case=TRUE)] <- 6
x$occupation_reactivetb[grepl("^NU",x$occupation_reactivetb,ignore.case=TRUE)] <- 7
x$occupation_reactivetb[grepl("^COO",x$occupation_reactivetb,ignore.case=TRUE)] <- 8
x$occupation_reactivetb[grepl("^DRI",x$occupation_reactivetb,ignore.case=TRUE)] <- 9
x$occupation_reactivetb[x$occupation_reactivetb=="HOME-MOTHER"]<-5
x$occupation_reactivetb[x$occupation_reactivetb=="HOME-FATHER"]<-10
```


```{r Reactive TB Sex}
x$sex_reactivetb[x$sex_reactivetb=="MALE"]<-1
x$sex_reactivetb[x$sex_reactivetb=="M"]<-1
x$sex_reactivetb[x$sex_reactivetb=="male"]<-1
x$sex_reactivetb[x$sex_reactivetb=="m"]<-1
x$sex_reactivetb[x$sex_reactivetb=="FEMALE"]<-2
x$sex_reactivetb[x$sex_reactivetb=="F"]<-2
x$sex_reactivetb[x$sex_reactivetb=="female"]<-2
x$sex_reactivetb[x$sex_reactivetb=="f"]<-2

```

```{r Country}
x$birth_place_reactivetb[!grepl("^IND|^TIB|^NEP|^BHU", x$birth_place_reactivetb,ignore.case=TRUE)] <- 5
x$birth_place_reactivetb[x$birth_place_reactivetb=="INDIA"]<-1
x$birth_place_reactivetb[x$birth_place_reactivetb=="TIBET"]<-2
x$birth_place_reactivetb[x$birth_place_reactivetb=="NEPAL"]<-3
x$birth_place_reactivetb[x$birth_place_reactivetb=="BHUTAN"]<-4
```

```{r reactive TB}
x$prev_therapy[grepl("NA",x$prev_therapy,ignore.case=TRUE)]<-""
x$prev_therapy[grepl("RECE",x$prev_therapy,ignore.case=TRUE)]<-1
x$prev_therapy[grepl("^NOT RECE",x$prev_therapy,ignore.case=TRUE)]<-2
x$prev_therapy[grepl("^C",x$prev_therapy,ignore.case=TRUE)]<-3
x$prev_therapy[grepl("^NOT RE",x$prev_therapy,ignore.case=TRUE)]<-5
x$prev_therapy[grepl("^A",x$prev_therapy,ignore.case=TRUE)]<-6
x$prev_therapy[grepl("^TB",x$prev_therapy,ignore.case=TRUE)]<-6

x$prev_therapy_reg[grepl("NA",x$prev_therapy_reg,ignore.case=TRUE)]<-""
x$prev_therapy_reg[grepl("4R",x$prev_therapy_reg,ignore.case=TRUE)]<-1
x$prev_therapy_reg[grepl("3HR",x$prev_therapy_reg,ignore.case=TRUE)]<-2
x$prev_therapy_reg[grepl("6H",x$prev_therapy_reg,ignore.case=TRUE)]<-3
x$prev_therapy_reg[grepl("3HP",x$prev_therapy_reg,ignore.case=TRUE)]<-4

x$prevther_adr[grepl("NA",x$prevther_adr,ignore.case=TRUE)]<-""
x$prevther_adr[grepl("^N",x$prevther_adr,ignore.case=TRUE)]<-0
x$prevther_adr[grepl("^Y",x$prevther_adr,ignore.case=TRUE)]<-1

x$culprit_drug[grepl("NA",x$culprit_drug ,ignore.case=TRUE)]<-""
x$culprit_drug[grepl("Rif",x$culprit_drug,ignore.case=TRUE)]<-1
x$culprit_drug[grepl("^I",x$culprit_drug,ignore.case=TRUE)]<-2
x$culprit_drug[grepl("Rif-Inh",x$culprit_drug,ignore.case=TRUE)]<-3

x$totalbil_1[grepl("NA",x$totalbil_1 ,ignore.case=TRUE)]<-""
x$directl_1[grepl("NA",x$directl_1,ignore.case=TRUE)]<-""
x$sgpt_1[grepl("NA",x$sgpt_1,ignore.case=TRUE)]<-""
x$sgot_1[grepl("NA",x$sgot_1,ignore.case=TRUE)]<-""
x$totalbil_2[grepl("NA",x$totalbil_2,ignore.case=TRUE)]<-""
x$directbil_2[grepl("NA", x$directbil_2,ignore.case=TRUE)]<-""
x$sgpt_2[grepl("NA",x$sgpt_2,ignore.case=TRUE)]<-""
x$sgot_2[grepl( "NA",x$sgot_2,ignore.case=TRUE)]<-""
x$totalbil_3[grepl("NA",x$totalbil_3,ignore.case=TRUE)]<-""
x$directbil_3[grepl("NA",x$directbil_3,ignore.case=TRUE)]<-""
x$sgpt_3[grepl("NA",x$sgpt_3,ignore.case=TRUE)]<-""
x$sgot_3[grepl("NA",x$sgot_3,ignore.case=TRUE)]<-""
x$totalbil_4[grepl("NA",x$totalbil_4,ignore.case=TRUE)]<-""
x$directbil_4[grepl("NA",x$directbil_4,ignore.case=TRUE)]<-""
x$sgpt_4[grepl("NA",x$sgpt_4,ignore.case=TRUE)]<-""
x$sgot_4[grepl("NA",x$sgot_4,ignore.case=TRUE)]<-""

x$prevtherapy_held[grepl("NA",x$prevtherapy_held,ignore.case=TRUE)]<-""
x$prevtherapy_held[grepl("^N",x$prevtherapy_held,ignore.case=TRUE)]<-0
x$prevtherapy_held[grepl("^Y",x$prevtherapy_held,ignore.case=TRUE)]<-1

x$prev_therapy_revised[grepl("NA",x$prev_therapy_revised,ignore.case=TRUE)]<-""
x$prev_therapy_revised[grepl("^N",x$prev_therapy_revised,ignore.case=TRUE)]<-0
x$prev_therapy_revised[grepl("^Y",x$prev_therapy_revised,ignore.case=TRUE)]<-1

x$revised_prevther_reg[grepl("NA",x$revised_prevther_reg,ignore.case=TRUE)]<-""
x$revised_prevther_reg[grepl("^4",x$revised_prevther_reg,ignore.case=TRUE)]<-1
x$revised_prevther_reg[grepl("^3HR",x$revised_prevther_reg,ignore.case=TRUE)]<-2
x$revised_prevther_reg[grepl("^6",x$revised_prevther_reg,ignore.case=TRUE)]<-3
x$revised_prevther_reg[grepl("^3HP",x$revised_prevther_reg,ignore.case=TRUE)]<-4
x$revised_prevther_reg[!grepl("^4|^3HR|^6|^3HP|^NA", x$revised_prevther_reg,ignore.case=TRUE)]<- ""

x$prevther_outcome[grepl("NA",x$prevther_outcome,ignore.case=TRUE)]<-""
x$prevther_outcome[grepl("^COM",x$prevther_outcome,ignore.case=TRUE)]<-1
x$prevther_outcome[grepl("^L",x$prevther_outcome,ignore.case=TRUE)]<-2
x$prevther_outcome[grepl("^A",x$prevther_outcome,ignore.case=TRUE)]<-3
x$prevther_outcome[grepl("TB",x$prevther_outcome,ignore.case=TRUE)]<-3
x$prevther_outcome[!grepl("NA|^COM|^L|^A|TB", x$prevther_outcome,ignore.case=TRUE)]<- 4

x$prevther_stopped_premature[grepl("NA",x$prevther_stopped_premature,ignore.case=TRUE)]<-""
x$prevther_stopped_premature[grepl("^N",x$prevther_stopped_premature,ignore.case=TRUE)]<-0
x$prevther_stopped_premature[grepl("^Y",x$prevther_stopped_premature,ignore.case=TRUE)]<-1

x$prevther_stopped_reason[grepl("NA",x$prevther_stopped_reason,ignore.case=TRUE)]<-""
x$prevther_stopped_reason[grepl("^H",x$prevther_stopped_reason,ignore.case=TRUE)]<- 1
x$prevther_stopped_reason[grepl("^other tox",x$prevther_stopped_reason,ignore.case=TRUE)]<- 2
x$prevther_stopped_reason[grepl("^discont",x$prevther_stopped_reason,ignore.case=TRUE)]<- 3
x$prevther_stopped_reason[!grepl("NA|^H|^other tox|^discont", x$prevther_stopped_reason,ignore.case=TRUE)]<- 4


```

```{r dates}
x$enroll_date_reactivetb[grepl("NA",x$enroll_date_reactivetb,ignore.case=TRUE)]<-""
x$prevther_startdate[grepl("NA",x$prevther_startdate,ignore.case=TRUE)]<-""
x$date_prevther_held[grepl("NA",x$date_prevther_held,ignore.case=TRUE)]<-""
x$date_prevther_restarted[grepl("NA",x$date_prevther_restarted,ignore.case=TRUE)]<-""
x$date_rx_start = mdy(x$date_rx_start)
x$date_rx_stopped = mdy(x$date_rx_stopped)
```

```{r complete}
x$main_database_demographics_complete<-2
x$main_database_tbinvestigation_complete<-2
x$active_tb_tbinvestigation_complete<-2
x$tst_reactive_demographics_complete<-2
x$tst_reactive_treatment_complete<-2
```

```{r write}
write.csv(x,"C:/Users/anish/Documents/Zero TB in Kids/GCTV 2018 TST_REACTIVE_clean.csv", na="")


```
